site_name: PSCM Resolver
repo_url: https://github.com/srcid/pscm-resolver
repo_name: srcid/pscm-resolver
edit_uri: tree/master/docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - styles/extra.css